[project]
name = "cmte-check"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "httpx>=0.28.1",
    "polars>=1.31.0",
    "streamlit>=1.46.1",
]
